 
spring:
    datasource:
        name: source
        url: jdbc:mysql://127.0.0.1:3306/shopping?characterEncoding=utf8
        username: root
        password: 123
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    main:  #springboot2.6要开启允许循环依赖
       allow-circular-references: true

mybatis: 
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.hz.ssm.pojo

# 分页配置
pagehelper:
    helper-dialect: mysql
    reasonable: true
    support-methods-arguments: true
    params: count=countSql


